#!/usr/bin/env bash

IP=$1
PROJECTNAME=$2

echo "[+] Scanning for $IP started... project name: $PROJECTNAME"

echo "...Scanning for common ports..."
nmap -Pn -oN "$PROJECTNAME.short.net.txt" $IP 

echo "...common port scan ready, scanning from 1-10000"
nmap -Pn -p1-10000 -oN "$PROJECTNAME.0010.net.txt" $IP

echo "...common port scan ready, scanning from 10000-20000"
nmap -Pn -p10000-20000 -oN "$PROJECTNAME.1020.net.txt" $IP

echo "...common port scan ready, scanning from 30000-40000"
nmap -Pn -p20000-30000 -oN "$PROJECTNAME.3040.net.txt" $IP

echo "...common port scan ready, scanning from 40000-50000"
nmap -Pn -p30000-40000 -oN "$PROJECTNAME.4050.net.txt" $IP

echo "...common port scan ready, scanning from 40000-50000"
nmap -Pn -p40000-50000 -oN "$PROJECTNAME.4050.net.txt" $IP

echo "...common port scan ready, scanning from 50000-65535"
nmap -Pn -p50000-65535 -oN "$PROJECTNAME.5060.net.txt" $IP

echo "[+] DONE!"
